# Code snippet taken directly and edited from the DDNet codebase.
# Teeworlds Copyright (C) 2007-2014 Magnus Auvinen
# DDRace    Copyright (C) 2010-2011 Shereef Marzouk
# DDNet     Copyright (C) 2013-2022 Dennis Felsing

from datatypes import Array, Float, Int, Pointer, String, Struct, TextureHandle

class Image(Struct):
	def __init__(self, name="", filename=""):
		Struct.__init__(self, "CDataImage")
		self.name = String(name)
		self.filename = String(filename)
		self.id = TextureHandle()

class SpriteSet(Struct):
	def __init__(self, name="", image=None, gridx=0, gridy=0):
		Struct.__init__(self, "CDataSpriteset")
		self.name = String(name)
		self.image = Pointer(Image, image) # TODO
		self.gridx = Int(gridx)
		self.gridy = Int(gridy)
		
class Sprite(Struct):
	def __init__(self, name="", Set=None, location="", x=0, y=0, w=0, h=0):
		Struct.__init__(self, "CDataSprite")
		self.name = String(name)
		self.set = Pointer(SpriteSet, Set) # TODO
		self.location = String(location)
		self.x = Int(x)
		self.y = Int(y)
		self.w = Int(w)
		self.h = Int(h)
		
class DataContainer(Struct):
	def __init__(self):
		Struct.__init__(self, "CDataContainer")
		self.images = Array(Image())
		self.spritesets = Array(SpriteSet())
		self.sprites = Array(Sprite())
		
container = DataContainer()

image_null = Image("null", "")
image_particles = Image("particles", "particles.png")
image_game = Image("game", "game.png")
image_cursor = Image("cursor", "gui_cursor.png")
image_banner = Image("banner", "gui_logo.png")
image_editor_cursor = Image("editor_cursor", "cursor.png")
image_emoticons = Image("emoticons", "emoticons.png")
image_console_bg = Image("console_bg", "console.png")
image_console_bar = Image("console_bar", "console_bar.png")
image_speedup_arrow = Image("speedup_arrow", "speed_arrow.png")
image_guibuttons = Image("guibuttons", "gui_buttons.png")
image_guiicons = Image("guiicons", "gui_icons.png")
image_arrow = Image("arrow", "arrow.png")
image_audio_source = Image("audio_source", "audio_source.png")
image_strongweak = Image("strongweak", "strong_weak.png")
image_hud = Image("hud", "hud.png")
image_extras = Image("extras", "extras.png")

container.images.Add(image_null)
container.images.Add(image_game)
container.images.Add(image_particles)
container.images.Add(image_cursor)
container.images.Add(image_editor_cursor)
container.images.Add(image_banner)
container.images.Add(image_emoticons)
container.images.Add(image_console_bg)
container.images.Add(image_console_bar)
container.images.Add(image_speedup_arrow)
container.images.Add(image_guibuttons)
container.images.Add(image_guiicons)
container.images.Add(image_arrow)
container.images.Add(image_audio_source)
container.images.Add(image_strongweak)
container.images.Add(image_hud)
container.images.Add(image_extras)

set_null = SpriteSet("null", image_null, 1, 1)
set_particles = SpriteSet("particles", image_particles, 8, 8)
set_game = SpriteSet("game", image_game, 32, 16)
set_emoticons = SpriteSet("emoticons", image_emoticons, 4, 4)
set_guibuttons = SpriteSet("guibuttons", image_guibuttons, 12, 4)
set_guiicons = SpriteSet("guiicons", image_guiicons, 12, 2)
set_strongweak = SpriteSet("strongweak", image_strongweak, 2, 1)
set_hud = SpriteSet("hud", image_hud, 16, 16)
set_extras = SpriteSet("extras", image_extras, 16, 16)
set_speedup_arrow = SpriteSet("speedup_arrow", image_speedup_arrow, 1, 1)
set_audio_source = SpriteSet("audio_source", image_audio_source, 1, 1)
set_cursor = SpriteSet("cursor", image_cursor, 1, 1)
set_editor_cursor = SpriteSet("editor_cursor", image_editor_cursor, 1, 1)
set_banner = SpriteSet("banner", image_banner, 1, 1)
set_console_bg = SpriteSet("console_bg", image_console_bg, 1, 1)
set_console_bar = SpriteSet("console_bar", image_console_bar, 1, 1)
set_arrow = SpriteSet("arrow", image_arrow, 1, 1)

container.spritesets.Add(set_null)
container.spritesets.Add(set_game)
container.spritesets.Add(set_particles)
container.spritesets.Add(set_cursor)
container.spritesets.Add(set_editor_cursor)
container.spritesets.Add(set_banner)
container.spritesets.Add(set_emoticons)
container.spritesets.Add(set_console_bg)
container.spritesets.Add(set_console_bar)
container.spritesets.Add(set_speedup_arrow)
container.spritesets.Add(set_guibuttons)
container.spritesets.Add(set_guiicons)
container.spritesets.Add(set_arrow)
container.spritesets.Add(set_audio_source)
container.spritesets.Add(set_strongweak)
container.spritesets.Add(set_hud)
container.spritesets.Add(set_extras)

container.sprites.Add(Sprite("part_slice", set_particles, "particles", 0,0,1,1))
container.sprites.Add(Sprite("part_ball", set_particles, "particles", 1,0,1,1))
container.sprites.Add(Sprite("part_splat01", set_particles, "particles", 2,0,1,1))
container.sprites.Add(Sprite("part_splat02", set_particles, "particles", 3,0,1,1))
container.sprites.Add(Sprite("part_splat03", set_particles, "particles", 4,0,1,1))

container.sprites.Add(Sprite("part_smoke", set_particles, "particles", 0,1,1,1))
container.sprites.Add(Sprite("part_shell", set_particles, "particles", 0,2,2,2))
container.sprites.Add(Sprite("part_expl01", set_particles, "particles", 0,4,4,4))
container.sprites.Add(Sprite("part_airjump", set_particles, "particles", 2,2,2,2))
container.sprites.Add(Sprite("part_hit01", set_particles, "particles", 4,1,2,2))

container.sprites.Add(Sprite("health_full", set_game, "hud", 21,0,2,2))
container.sprites.Add(Sprite("health_empty", set_game, "hud", 23,0,2,2))
container.sprites.Add(Sprite("armor_full", set_game, "hud", 21,2,2,2))
container.sprites.Add(Sprite("armor_empty", set_game, "hud", 23,2,2,2))

container.sprites.Add(Sprite("star1", set_game, "particles", 15,0,2,2))
container.sprites.Add(Sprite("star2", set_game, "particles", 17,0,2,2))
container.sprites.Add(Sprite("star3", set_game, "particles", 19,0,2,2))

container.sprites.Add(Sprite("part1", set_game, "particles", 6,0,1,1))
container.sprites.Add(Sprite("part2", set_game, "particles", 6,1,1,1))
container.sprites.Add(Sprite("part3", set_game, "particles", 7,0,1,1))
container.sprites.Add(Sprite("part4", set_game, "particles", 7,1,1,1))
container.sprites.Add(Sprite("part5", set_game, "particles", 8,0,1,1))
container.sprites.Add(Sprite("part6", set_game, "particles", 8,1,1,1))
container.sprites.Add(Sprite("part7", set_game, "particles", 9,0,2,2))
container.sprites.Add(Sprite("part8", set_game, "particles", 11,0,2,2))
container.sprites.Add(Sprite("part9", set_game, "particles", 13,0,2,2))

container.sprites.Add(Sprite("weapon_gun_body", set_game, "weapons", 2,4,4,2))
container.sprites.Add(Sprite("weapon_gun_cursor", set_game, "weapons", 0,4,2,2))
container.sprites.Add(Sprite("weapon_gun_proj", set_game, "weapons", 6,4,2,2))
container.sprites.Add(Sprite("weapon_gun_muzzle1", set_game, "weapons", 8,4,4,2))
container.sprites.Add(Sprite("weapon_gun_muzzle2", set_game, "weapons", 12,4,4,2))
container.sprites.Add(Sprite("weapon_gun_muzzle3", set_game, "weapons", 16,4,4,2))

container.sprites.Add(Sprite("weapon_shotgun_body", set_game, "weapons", 2,6,8,2))
container.sprites.Add(Sprite("weapon_shotgun_cursor", set_game, "weapons", 0,6,2,2))
container.sprites.Add(Sprite("weapon_shotgun_proj", set_game, "weapons", 10,6,2,2))
container.sprites.Add(Sprite("weapon_shotgun_muzzle1", set_game, "weapons", 12,6,4,2))
container.sprites.Add(Sprite("weapon_shotgun_muzzle2", set_game, "weapons", 16,6,4,2))
container.sprites.Add(Sprite("weapon_shotgun_muzzle3", set_game, "weapons", 20,6,4,2))

container.sprites.Add(Sprite("weapon_grenade_body", set_game, "weapons", 2,8,7,2))
container.sprites.Add(Sprite("weapon_grenade_cursor", set_game, "weapons", 0,8,2,2))
container.sprites.Add(Sprite("weapon_grenade_proj", set_game, "weapons", 10,8,2,2))

container.sprites.Add(Sprite("weapon_hammer_body", set_game, "weapons", 2,1,4,3))
container.sprites.Add(Sprite("weapon_hammer_cursor", set_game, "weapons", 0,0,2,2))
container.sprites.Add(Sprite("weapon_hammer_proj", set_game, "weapons", 0,0,0,0))

container.sprites.Add(Sprite("weapon_ninja_body", set_game, "weapons", 2,10,8,2))
container.sprites.Add(Sprite("weapon_ninja_cursor", set_game, "weapons", 0,10,2,2))
container.sprites.Add(Sprite("weapon_ninja_proj", set_game, "weapons", 0,0,0,0))

container.sprites.Add(Sprite("weapon_laser_body", set_game, "weapons", 2,12,7,3))
container.sprites.Add(Sprite("weapon_laser_cursor", set_game, "weapons", 0,12,2,2))
container.sprites.Add(Sprite("weapon_laser_proj", set_game, "weapons", 10,12,2,2))

container.sprites.Add(Sprite("hook_chain", set_game, "weapons", 2,0,1,1))
container.sprites.Add(Sprite("hook_head", set_game, "weapons", 3,0,2,1))

container.sprites.Add(Sprite("weapon_ninja_muzzle1", set_game, "weapons", 25,0,7,4))
container.sprites.Add(Sprite("weapon_ninja_muzzle2", set_game, "weapons", 25,4,7,4))
container.sprites.Add(Sprite("weapon_ninja_muzzle3", set_game, "weapons", 25,8,7,4))

container.sprites.Add(Sprite("pickup_misc", set_game, "map_items", 8,2,2,2))
container.sprites.Add(Sprite("pickup_health", set_game, "map_items", 10,2,2,2))
container.sprites.Add(Sprite("pickup_armor", set_game, "map_items", 12,2,2,2))
container.sprites.Add(Sprite("pickup_armor_shotgun", set_game, "map_items", 15,2,2,2))
container.sprites.Add(Sprite("pickup_armor_grenade", set_game, "map_items", 17,2,2,2))
container.sprites.Add(Sprite("pickup_armor_ninja", set_game, "map_items", 10,10,2,2))
container.sprites.Add(Sprite("pickup_armor_laser", set_game, "map_items", 19,2,2,2))

container.sprites.Add(Sprite("flag_blue", set_game, "map_items", 12,8,4,8))
container.sprites.Add(Sprite("flag_red", set_game, "map_items", 16,8,4,8))

container.sprites.Add(Sprite("oop", set_emoticons, "emoticons", 0, 0, 1, 1))
container.sprites.Add(Sprite("exclamation", set_emoticons, "emoticons", 1, 0, 1, 1))
container.sprites.Add(Sprite("hearts", set_emoticons, "emoticons", 2, 0, 1, 1))
container.sprites.Add(Sprite("drop", set_emoticons, "emoticons", 3, 0, 1, 1))
container.sprites.Add(Sprite("dotdot", set_emoticons, "emoticons", 0, 1, 1, 1))
container.sprites.Add(Sprite("music", set_emoticons, "emoticons", 1, 1, 1, 1))
container.sprites.Add(Sprite("sorry", set_emoticons, "emoticons", 2, 1, 1, 1))
container.sprites.Add(Sprite("ghost", set_emoticons, "emoticons", 3, 1, 1, 1))
container.sprites.Add(Sprite("sushi", set_emoticons, "emoticons", 0, 2, 1, 1))
container.sprites.Add(Sprite("splattee", set_emoticons, "emoticons", 1, 2, 1, 1))
container.sprites.Add(Sprite("deviltee", set_emoticons, "emoticons", 2, 2, 1, 1))
container.sprites.Add(Sprite("zomg", set_emoticons, "emoticons", 3, 2, 1, 1))
container.sprites.Add(Sprite("zzz", set_emoticons, "emoticons", 0, 3, 1, 1))
container.sprites.Add(Sprite("wtf", set_emoticons, "emoticons", 1, 3, 1, 1))
container.sprites.Add(Sprite("eyes", set_emoticons, "emoticons", 2, 3, 1, 1))
container.sprites.Add(Sprite("question", set_emoticons, "emoticons", 3, 3, 1, 1))

container.sprites.Add(Sprite("speedup_arrow", set_speedup_arrow, "gui", 0,0,1,1))

container.sprites.Add(Sprite("guibutton_off", set_guibuttons, "gui", 0,0,4,4))
container.sprites.Add(Sprite("guibutton_on", set_guibuttons, "gui", 4,0,4,4))
container.sprites.Add(Sprite("guibutton_hover", set_guibuttons, "gui", 8,0,4,4))

container.sprites.Add(Sprite("guiicon_mute", set_guiicons, "gui", 0,0,4,2))
container.sprites.Add(Sprite("guiicon_emoticon_mute", set_guiicons, "gui", 4,0,4,2))
container.sprites.Add(Sprite("guiicon_friend", set_guiicons, "gui", 8,0,4,2))

container.sprites.Add(Sprite("audio_source", set_audio_source, "gui", 0,0,1,1))

container.sprites.Add(Sprite("hook_strong", set_strongweak, "hud",0,0,1,1))
container.sprites.Add(Sprite("hook_weak", set_strongweak, "hud",1,0,1,1))

container.sprites.Add(Sprite("hud_airjump", set_hud, "hud", 0,0,2,2))
container.sprites.Add(Sprite("hud_airjump_empty", set_hud, "hud", 2,0,2,2))
container.sprites.Add(Sprite("hud_solo", set_hud, "hud", 4,0,2,2))
container.sprites.Add(Sprite("hud_collision_disabled", set_hud, "hud", 6,0,2,2))
container.sprites.Add(Sprite("hud_endless_jump", set_hud, "hud", 8,0,2,2))
container.sprites.Add(Sprite("hud_endless_hook", set_hud, "hud", 10,0,2,2))
container.sprites.Add(Sprite("hud_jetpack", set_hud, "hud", 12,0,2,2))
container.sprites.Add(Sprite("hud_freeze_bar_full_left", set_hud, "hud", 0,2,1,1))
container.sprites.Add(Sprite("hud_freeze_bar_full", set_hud, "hud", 1,2,1,1))
container.sprites.Add(Sprite("hud_freeze_bar_empty", set_hud, "hud", 2,2,1,1))
container.sprites.Add(Sprite("hud_freeze_bar_empty_right", set_hud, "hud", 3,2,1,1))
container.sprites.Add(Sprite("hud_ninja_bar_full_left", set_hud, "hud", 0,3,1,1))
container.sprites.Add(Sprite("hud_ninja_bar_full", set_hud, "hud", 1,3,1,1))
container.sprites.Add(Sprite("hud_ninja_bar_empty", set_hud, "hud", 2,3,1,1))
container.sprites.Add(Sprite("hud_ninja_bar_empty_right", set_hud, "hud", 3,3,1,1))
container.sprites.Add(Sprite("hud_hook_hit_disabled", set_hud, "hud", 4,2,2,2))
container.sprites.Add(Sprite("hud_hammer_hit_disabled", set_hud, "hud", 6,2,2,2))
container.sprites.Add(Sprite("hud_shotgun_hit_disabled", set_hud, "hud", 8,2,2,2))
container.sprites.Add(Sprite("hud_grenade_hit_disabled", set_hud, "hud", 10,2,2,2))
container.sprites.Add(Sprite("hud_laser_hit_disabled", set_hud, "hud", 12,2,2,2))
container.sprites.Add(Sprite("hud_gun_hit_disabled", set_hud, "hud", 14,2,2,2))
container.sprites.Add(Sprite("hud_deep_frozen", set_hud, "hud", 10,4,2,2))
container.sprites.Add(Sprite("hud_live_frozen", set_hud, "hud", 12,4,2,2))
container.sprites.Add(Sprite("hud_teleport_grenade", set_hud, "hud", 4,4,2,2))
container.sprites.Add(Sprite("hud_teleport_gun", set_hud, "hud", 6,4,2,2))
container.sprites.Add(Sprite("hud_teleport_laser", set_hud, "hud", 8,4,2,2))
container.sprites.Add(Sprite("hud_practice_mode", set_hud, "hud", 4,6,2,2))
container.sprites.Add(Sprite("hud_dummy_hammer", set_hud, "hud", 6,6,2,2))
container.sprites.Add(Sprite("hud_dummy_copy", set_hud, "hud", 8,6,2,2))

container.sprites.Add(Sprite("part_snowflake", set_extras, "particles", 0,0,2,2))

container.sprites.Add(Sprite("cursor", set_cursor, "gui", 0,0,1,1))
container.sprites.Add(Sprite("editor_cursor", set_editor_cursor, "gui", 0,0,1,1))
container.sprites.Add(Sprite("banner", set_banner, "gui", 0,0,1,1))
container.sprites.Add(Sprite("console_bg", set_console_bg, "gui", 0,0,1,1))
container.sprites.Add(Sprite("console_bar", set_console_bar, "gui", 0,0,1,1))
container.sprites.Add(Sprite("arrow", set_arrow, "hud", 0,0,1,1))